name: Feature request
about: Suggest an idea for this project
labels: enhancement

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What's the feature about?
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
