import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { HelpCircle } from 'lucide-react';
import { CursorDataRow } from '@/pages/Index';
import { useSettings } from "@/contexts/SettingsContext";

interface DashboardMetricsProps {
  data: CursorDataRow[];
  originalData: CursorDataRow[];
  baseFilteredData: CursorDataRow[];
}

export const DashboardMetrics = ({ data, originalData, baseFilteredData }: DashboardMetricsProps) => {
  const { settings } = useSettings();

  const metrics = useMemo(() => {
    // Use baseFilteredData for totals (respects user/date filters but not time period)
    const totalAcceptedLines = baseFilteredData.reduce((sum, row) => {
      // Skip aggregated rows
      if (row.Email.includes('active users')) return sum;
      return sum + (parseInt(row['Chat Accepted Lines Added']) || 0);
    }, 0);

    const activeUsers = new Set(
      baseFilteredData
        .filter(row => !row.Email.includes('active users')) // Skip aggregated rows
        .filter(row => row['Is Active'] === 'true')
        .map(row => row.Email)
    ).size;

    // Calculate acceptance rate from filtered data (should be affected by time period)
    const filteredAcceptedLines = data.reduce((sum, row) => {
      return sum + (parseInt(row['Chat Accepted Lines Added']) || 0);
    }, 0);

    const filteredSuggestedLines = data.reduce((sum, row) => {
      return sum + (parseInt(row['Chat Suggested Lines Added']) || 0);
    }, 0);

    const acceptanceRate = filteredSuggestedLines > 0 
      ? ((filteredAcceptedLines / filteredSuggestedLines) * 100).toFixed(1)
      : '0';

    // Estimate dev hours saved (dynamic lines per minute)
    const estimatedHoursSaved = Math.round(totalAcceptedLines / (settings.linesPerMinute * 60));

    // Calculate money saved (existing metric)
    const estimatedMoneySaved = estimatedHoursSaved * settings.pricePerHour;

    // Calculate annual Cursor cost
    const annualCursorCost = activeUsers * settings.cursorPricePerUser * 12;

    // Calculate ROI as a percentage
    const roi = annualCursorCost > 0 
      ? ((estimatedMoneySaved / annualCursorCost) * 100).toFixed(1)
      : '0';

    return {
      totalAcceptedLines: totalAcceptedLines.toLocaleString(),
      activeUsers,
      acceptanceRate: `${acceptanceRate}%`,
      estimatedHoursSaved: estimatedHoursSaved.toLocaleString(),
      estimatedMoneySaved: `$${estimatedMoneySaved.toLocaleString()}`,
      roi: `${roi}%`,
    };
  }, [data, originalData, baseFilteredData, settings.linesPerMinute, settings.pricePerHour, settings.cursorPricePerUser]);

  const metricCards = [
    {
      title: 'Code Generated by AI',
      value: metrics.totalAcceptedLines,
      gradient: 'from-blue-500 to-blue-600',
      tooltip: <>
        <strong>What it means:</strong> The total amount of code produced via AI suggestions (accepted lines), showing the business impact of AI adoption across your team.
        <br/><br/>
        <strong>Why it matters:</strong> More code by AI can mean faster feature delivery, freeing up engineers for higher-value work.
        <br/><br/>
        <em>(Not affected by time period selection)</em>
      </>
    },
    {
      title: 'AI Suggestion Acceptance Rate',
      value: metrics.acceptanceRate,
      gradient: 'from-emerald-500 to-emerald-600',
      tooltip: <>
        <strong>What it means:</strong> The share of suggested lines your team accepts from AI, reflecting developer trust and AI usability.
        <br/><br/>
        <strong>Why it matters:</strong> Higher rates suggest greater value from AI—industry benchmarks: 10-30% = typical, 30%+ = excellent.
        <br/><br/>
        <strong>Action:</strong> Encourage best practice sharing to boost adoption.
      </>
    },
    {
      title: 'Development Time Saved (Hours)',
      value: metrics.estimatedHoursSaved,
      gradient: 'from-teal-500 to-teal-600',
      tooltip: <>
        <strong>What it means:</strong> Total developer hours saved by using AI-powered suggestions, based on your team’s coding speed.
        <br/><br/>
        <strong>Why it matters:</strong> Reclaim time for innovation and complex problem solving.
        <br/><br/>
        <strong>Tip:</strong> Adjust your team’s “Coding Speed” in settings for precise reporting.
        <br/><br/>
        <em>(Not affected by time period selection)</em>
      </>
    },
    {
      title: 'Development Cost Savings',
      value: metrics.estimatedMoneySaved,
      gradient: 'from-green-500 to-green-600',
      tooltip: <>
        <strong>What it means:</strong> Total estimated cost your team avoided by using AI to speed up coding (developer time valued at your set hourly rate).
        <br/><br/>
        <strong>Why it matters:</strong> Track the real dollar impact of AI for budget decisions.
        <br/><br/>
        <strong>Industry benchmark:</strong> Median developer hourly rates: $50–$120 USD.
        <br/><br/>
        <em>(Not affected by time period selection)</em>
      </>
    },
    {
      title: 'ROI - Cursor Investment Return',
      value: metrics.roi,
      gradient: 'from-purple-500 to-purple-600',
      tooltip: <>
        <strong>What it means:</strong> Your return on investment from using Cursor, comparing savings to annual license cost.
        <br/><br/>
        <strong>Why it matters:</strong> A higher percentage means better AI payback for your budget.
        <br/><br/>
        <strong>Action:</strong> Use this to justify AI expenses to leadership.
        <br/><br/>
        <em>Annual cost = {metrics.activeUsers} users × ${settings.cursorPricePerUser}/month × 12 months</em>
      </>
    },
    {
      title: 'Active Users',
      value: metrics.activeUsers.toString(),
      gradient: 'from-indigo-500 to-indigo-600',
      tooltip: <>
        <strong>What it means:</strong> Number of distinct, active AI adopters on your team.
        <br/><br/>
        <strong>Why it matters:</strong> More active users means greater return and spreading best practices.
        <br/><br/>
        <strong>Tip:</strong> Spot trends in adoption and help non-active users unlock value.
        <br/><br/>
        <em>(Not affected by time period selection)</em>
      </>
    },
  ];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-6">
      {metricCards.map((metric, index) => (
        <Card key={index} className="overflow-hidden h-full">
          <CardHeader className={`bg-gradient-to-br ${metric.gradient} text-white pb-3 min-h-[80px] flex flex-col justify-center`}>
            <div className="flex items-start justify-between gap-2">
              <CardTitle className="text-sm font-medium opacity-90 leading-tight flex-1">
                {metric.title}
              </CardTitle>
              <Popover>
                <PopoverTrigger className="shrink-0">
                  <HelpCircle className="h-4 w-4 text-white opacity-75 hover:opacity-100 hover:scale-110 transition-all cursor-pointer" />
                </PopoverTrigger>
                <PopoverContent>
                  <p className="max-w-xs">{metric.tooltip}</p>
                </PopoverContent>
              </Popover>
            </div>
          </CardHeader>
          <CardContent className="pt-6 pb-6 flex items-center justify-center min-h-[80px]">
            <div className="text-3xl font-bold text-foreground text-center">
              {metric.value}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
};
